version: 0.2

env:
  variables:
    CONTAINER_NAME: "api"   # Debe ser el "name" del contenedor en la Task Definition

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Instalando deps…"
      - npm ci --legacy-peer-deps

  pre_build:
    commands:
      # Ajusta tu repo ECR exacto (cópialo del proyecto/pipeline)
      - REPO_URI="810772959670.dkr.ecr.us-east-2.amazonaws.com/simple-docker-service-0699eddab4e7"
      - IMAGE_TAG=$(date +%Y%m%d%H%M%S)
      - echo "Repo=$REPO_URI | Tag=$IMAGE_TAG"
      - aws ecr get-login-password --region us-east-2 \
        | docker login --username AWS --password-stdin 810772959670.dkr.ecr.us-east-2.amazonaws.com

  build:
    commands:
      - echo "Construyendo imagen…"
      - docker build -t "$REPO_URI:$IMAGE_TAG" -f apps/api/Dockerfile .
      - docker tag "$REPO_URI:$IMAGE_TAG" "$REPO_URI:latest"

  post_build:
    commands:
      - echo "Publicando imagen…"
      - docker push "$REPO_URI:$IMAGE_TAG"
      - docker push "$REPO_URI:latest"
      - echo "IMAGEN=$REPO_URI:$IMAGE_TAG" > image-detail.txt

artifacts:
  files:
    - image-detail.txt